<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>Encomm.Stub.MSBuildTasks</AssemblyName>
    <RootNamespace>Encomm.Stub</RootNamespace>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Framework" Version="17.10.4" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.10.4" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\StubTasks\EncommStubTasks.cs" />
  </ItemGroup>
</Project>